In [1]:
import numpy as np

In [24]:
a=np.arange(6)
a=a.reshape((2,3))
print(a)
b=np.arange(10,28,2)
b=b.reshape((3,3))
print(b)

[[0 1 2]
 [3 4 5]]
[[10 12 14]
 [16 18 20]
 [22 24 26]]


In [25]:
a=a[:,np.newaxis,:]
print(a.shape)
b=b[np.newaxis,:,:]
print(b.shape)

(2, 1, 3)
(1, 3, 3)


In [30]:
c=a-b
c=np.abs(c)
c=np.sum(c, axis=2)
print(c)




[[33 51 69]
 [24 42 60]]
